package TragaMonedas;


import CLASES_CASILLAS.Casilla1;
import CLASES_CASILLAS.Casilla2;
import CLASES_CASILLAS.Casilla3;
import CLASES_CASILLAS.Casilla4;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class DiseñoMaquina extends javax.swing.JFrame {

    private int fondos = 0;  // Fondos iniciales
    private int apuesta = 0;   // Apuesta inicial
    
    Casilla1 c1;
    Casilla2 c2;
    Casilla3 c3;
    Casilla4 c4;
    
    boolean Resultadoc1 = false;
    boolean Resultadoc2 = false;
    boolean Resultadoc3 = false;
    boolean Resultadoc4 = false;
    
    public DiseñoMaquina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ico1 = new javax.swing.JLabel();
        Ico2 = new javax.swing.JLabel();
        Ico3 = new javax.swing.JLabel();
        Ico4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_iniciar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CantApostar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        IngresoFondos = new javax.swing.JTextField();
        CasillaIco1 = new javax.swing.JLabel();
        CasillaIco2 = new javax.swing.JLabel();
        CasillaIco3 = new javax.swing.JLabel();
        CasillaIco4 = new javax.swing.JLabel();
        Detener1 = new javax.swing.JButton();
        Detener2 = new javax.swing.JButton();
        Detener3 = new javax.swing.JButton();
        Detener4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        Ico1.setBackground(new java.awt.Color(255, 255, 255));
        Ico1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel6.setText("CASINO FORTUNA");

        bt_iniciar.setBackground(new java.awt.Color(255, 0, 0));
        bt_iniciar.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        bt_iniciar.setText("SUERTE!!!");
        bt_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_iniciarActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel7.setText("CREDITOS A APOSTAR");

        CantApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantApostarActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel8.setText("FONDOS");

        IngresoFondos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoFondosActionPerformed(evt);
            }
        });

        CasillaIco1.setIcon(new javax.swing.ImageIcon("D:\\UNIVERSIDAD\\DEBERES 3° Semestre\\PROGRAMACION III\\prog3-main\\labs\\06\\Tragamonedas\\src\\main\\java\\ICONOS\\Icono1.png")); // NOI18N

        CasillaIco2.setIcon(new javax.swing.ImageIcon("D:\\UNIVERSIDAD\\DEBERES 3° Semestre\\PROGRAMACION III\\prog3-main\\labs\\06\\Tragamonedas\\src\\main\\java\\ICONOS\\Icono2.png")); // NOI18N

        CasillaIco3.setIcon(new javax.swing.ImageIcon("D:\\UNIVERSIDAD\\DEBERES 3° Semestre\\PROGRAMACION III\\prog3-main\\labs\\06\\Tragamonedas\\src\\main\\java\\ICONOS\\Icono3.png")); // NOI18N

        CasillaIco4.setIcon(new javax.swing.ImageIcon("D:\\UNIVERSIDAD\\DEBERES 3° Semestre\\PROGRAMACION III\\prog3-main\\labs\\06\\Tragamonedas\\src\\main\\java\\ICONOS\\Icono4.png")); // NOI18N

        Detener1.setText("DETENER");
        Detener1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detener1ActionPerformed(evt);
            }
        });

        Detener2.setText("DETENER");
        Detener2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detener2ActionPerformed(evt);
            }
        });

        Detener3.setText("DETENER");
        Detener3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detener3ActionPerformed(evt);
            }
        });

        Detener4.setText("DETENER");
        Detener4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detener4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ico1)
                        .addGap(18, 18, 18)
                        .addComponent(Ico2)
                        .addGap(18, 18, 18)
                        .addComponent(Ico3)
                        .addGap(18, 18, 18)
                        .addComponent(Ico4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Detener1)
                                    .addComponent(CasillaIco1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CasillaIco2)
                                        .addGap(18, 18, 18)
                                        .addComponent(CasillaIco3)
                                        .addGap(18, 18, 18)
                                        .addComponent(CasillaIco4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Detener2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Detener3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Detener4))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IngresoFondos)
                            .addComponent(CantApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bt_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CasillaIco1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CasillaIco3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CasillaIco4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CasillaIco2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Ico3)
                        .addComponent(Ico4)
                        .addComponent(Ico1)
                        .addComponent(Ico2)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Detener1)
                    .addComponent(Detener2)
                    .addComponent(Detener3)
                    .addComponent(Detener4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(IngresoFondos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CantApostar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_iniciarActionPerformed
        
        fondos = Integer.parseInt(IngresoFondos.getText()); // Otra opción es asignar un valor inicial aquí
        apuesta = Integer.parseInt(CantApostar.getText()); 
        if (fondos >= apuesta) {
            
            int timems = 100;
        
            c1 = new Casilla1(timems);
            c2 = new Casilla2(timems);
            c3 = new Casilla3(timems);
            c4 = new Casilla4(timems);
        
            Resultadoc1 = false;
            Resultadoc2 = false;
            Resultadoc3 = false;
            Resultadoc4 = false;

            bt_iniciar.setEnabled(false);
        
            c1.start();
            c2.start();
            c3.start();
            c4.start();   
                   
        } else {
            JOptionPane.showMessageDialog(null, "No tienes fondos suficientes para realizar la apuesta.");
    }
        
    }//GEN-LAST:event_bt_iniciarActionPerformed

    private void Detener1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detener1ActionPerformed
        // TODO add your handling code here:
        c1.detenerCasilla();
        Resultadoc1 = true;
        DarResultado();
    }//GEN-LAST:event_Detener1ActionPerformed

    private void Detener2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detener2ActionPerformed
        // TODO add your handling code here:
        c2.detenerCasilla();
        Resultadoc2 = true;
        DarResultado();
    }//GEN-LAST:event_Detener2ActionPerformed

    private void Detener3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detener3ActionPerformed
        // TODO add your handling code here:
        c3.detenerCasilla();
        Resultadoc3 = true;
        DarResultado();
    }//GEN-LAST:event_Detener3ActionPerformed

    private void Detener4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detener4ActionPerformed
        // TODO add your handling code here:
        c4.detenerCasilla();
        Resultadoc4 = true;
        DarResultado();
    }//GEN-LAST:event_Detener4ActionPerformed

    private void IngresoFondosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoFondosActionPerformed
        // TODO add your handling code here:
        try {
            fondos = Integer.parseInt(IngresoFondos.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingresa un valor válido para los fondos.");
        }
    }//GEN-LAST:event_IngresoFondosActionPerformed

    private void CantApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantApostarActionPerformed
        // TODO add your handling code here:
        try {
            apuesta = Integer.parseInt(CantApostar.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingresa un valor válido para la apuesta.");
    }
    }//GEN-LAST:event_CantApostarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiseñoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiseñoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiseñoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiseñoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiseñoMaquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantApostar;
    public static javax.swing.JLabel CasillaIco1;
    public static javax.swing.JLabel CasillaIco2;
    public static javax.swing.JLabel CasillaIco3;
    public static javax.swing.JLabel CasillaIco4;
    private javax.swing.JButton Detener1;
    private javax.swing.JButton Detener2;
    private javax.swing.JButton Detener3;
    private javax.swing.JButton Detener4;
    private javax.swing.JLabel Ico1;
    private javax.swing.JLabel Ico2;
    private javax.swing.JLabel Ico3;
    private javax.swing.JLabel Ico4;
    private javax.swing.JTextField IngresoFondos;
    private javax.swing.JButton bt_iniciar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

private void DarResultado(){
    if(Resultadoc1 && Resultadoc2 && Resultadoc3 && Resultadoc4){
        
        try{
            Thread.sleep(100);
        }catch(InterruptedException ex){
            Logger.getLogger(Casilla1.class.getName()).log(Level.SEVERE, null, ex);
        }
        bt_iniciar.setEnabled(true);
        if(CasillaIco1.getIcon().toString().equals(CasillaIco2.getIcon().toString()) && 
                CasillaIco1.getIcon().toString().equals(CasillaIco3.getIcon().toString()) && 
                CasillaIco1.getIcon().toString().equals(CasillaIco4.getIcon().toString())){
            
            fondos += apuesta * 2;
            JOptionPane.showMessageDialog(null, "FELICIDADES, HAS GANADO!!");   
        }else{
            
            fondos = fondos - apuesta;
            JOptionPane.showMessageDialog(null, "VUELVE A INTENTARLO");
        }
        
        IngresoFondos.setText(Integer.toString(fondos));
        CantApostar.setText(Integer.toString(apuesta));
        bt_iniciar.setEnabled(true);
    }
}


}

